outfile:main.c add_begin.c add_mid.c add_end.c rev_print.c rev_link.c rev_data.c print.c del_rollbased.c delete_all.c
	cc main.c add_begin.c add_mid.c add_end.c rev_print.c rev_link.c rev_data.c print.c del_rollbased.c delete_all.c -o outfile
clean:
	rm -f student.o
