outfile:add_begin.c count_fun.c rollbased_delet.c add_end.c delet_all.c print.c add_mid.c main.c reverse_data.c rev_print.c rev_link.c
	cc add_begin.c count_fun.c rollbased_delet.c add_end.c delet_all.c print.c add_mid.c main.c reverse_data.c rev_link.c rev_print.c -o outfile
clean:
	rm -f student *.o
